sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - main
cache:
  directories:
  - node-modules
  - src
before_install:
- npm update
install:
- cd backend
- npm install
script:
- npm run test
# - npm run coveralls