sudo: false
language: node_js
node_js:
- node
branches:
  only:
  - main
cache:
  directories:
  - node-modules
  - backend
before_install:
- npm update
install:
- npm install
script:
- npm run test
# - npm run coveralls